### ISSUE TITLE
Cannot read property 'example' of undefined  at Array.authHeader

### ISSUE THREAD

**Issue by dmitrylebedev** [bukalapak/snowboard#108]
Hi, I'm have an TypeError when I enable `playground` option.

![image](https://user-images.githubusercontent.com/9784329/72810572-e9838080-3c6e-11ea-8244-7739a90a64bf.png)

![image](https://user-images.githubusercontent.com/9784329/72811216-3c116c80-3c70-11ea-8da8-5e124a49f7ce.png)

My config.yaml file
```yaml
html:
  playground:
    enabled: true
    env: easy
    environments:
      easy:
        playground: false
        url: /
      advanced:
        url:
```

api.apib file

```apib
**FORMAT: 1A
HOST: SERVICE_HOST

# SERVICE_NAME

# Group system
Системные методы

## Schema [/schema/api.apib]

### Get schema [GET]
Get api schema BluePrint

+ Request json (application/json)

    + Headers

            X-API-Key: api-key-string

+ Response 200
    + Attributes (object)**
```
